PREFIX lwb: <http://lexbib.elex.is/entity/>
PREFIX ldp: <http://lexbib.elex.is/prop/direct/>
PREFIX lp: <http://lexbib.elex.is/prop/>
PREFIX lps: <http://lexbib.elex.is/prop/statement/>
PREFIX lpq: <http://lexbib.elex.is/prop/qualifier/>
PREFIX lpr: <http://lexbib.elex.is/prop/reference/>
PREFIX lno: <http://lexbib.elex.is/prop/novalue/>

select distinct ?prop ?propLabel ?wikidata ?equivProp where
{
?bibitem ldp:P5 lwb:Q3 ;
         ?p ?o.
?prop wikibase:directClaim ?p;
      rdfs:label ?propLabel. filter(lang(?propLabel)="en")
  OPTIONAL {?prop ldp:P2 ?wikidata.}
  OPTIONAL {?prop ldp:P34 ?equivProp.}
  }
