# Elexifinder collection and image links

images = {
1 : "https://elex.is/wp-content/uploads/2020/12/collection_1_elex.jpg.",
2 : "https://elex.is/wp-content/uploads/2020/12/collection_2_euralex.jpg",
3 : "https://elex.is/wp-content/uploads/2020/12/collection_3_ijl.jpg",
4 : "https://elex.is/wp-content/uploads/2020/12/collection_4_lexikos.jpg",
5 : "https://elex.is/wp-content/uploads/2020/12/collection_5_lexiconordica.jpg",
6 : "https://elex.is/wp-content/uploads/2020/12/collection_6_lexicographica.jpg",
7 : "https://elex.is/wp-content/uploads/2020/12/collection_7_NSL.jpg",
8 : "https://elex.is/wp-content/uploads/2020/12/collection_8_lexicon_tokyo.jpg",
9 : "https://elex.is/wp-content/uploads/2020/12/collection_9_lexicography_asialex.jpg",
10 : "https://elex.is/wp-content/uploads/2020/12/collection_10_globalex.jpg",
11 : "https://elex.is/wp-content/uploads/2020/12/collection_11_videolectures.jpg",
12 : "https://elex.is/wp-content/uploads/collection_12.jpg",
13 : "https://elex.is/wp-content/uploads/2020/12/collection_13_teubert.jpg",
14 : "https://elex.is/wp-content/uploads/2020/12/collection_14_fuertesolivera.jpg",
15 : "https://elex.is/wp-content/uploads/2020/12/collection_15_mullerspitzer.jpg",
16 : "https://elex.is/wp-content/uploads/2020/12/collection_16_slovenscina.jpg",
17 : "https://elex.is/wp-content/uploads/2020/12/collection_17_rdelexicografia.jpg",
18 : "https://elex.is/wp-content/uploads/collection_18_bloomsbury.jpg",
19 : "https://elex.is/wp-content/uploads/collection_19_degruyter.jpg",
20 : "https://elex.is/wp-content/uploads/collection_20_degruyter.jpg",
21 : "https://elex.is/wp-content/uploads/collection_21_degruyter.jpg",
22 : "https://elex.is/wp-content/uploads/collection_22_benjamins.jpg",
23 : "https://elex.is/wp-content/uploads/collection_23_degruyter.jpg",
24 : "https://elex.is/wp-content/uploads/collection_24_degruyter.jpg",
25 : "https://elex.is/wp-content/uploads/collection_25_benjamins.jpg",
26 : "https://elex.is/wp-content/uploads/collection_26_dsna.jpg",
27 : "https://elex.is/wp-content/uploads/collection_27.jpg",
28 : "https://elex.is/wp-content/uploads/collection_28.jpg",
29 : "https://elex.is/wp-content/uploads/collection_29.jpg",

}
